--- #YAML:1.0
name:               Finance-Bank-IE
version:            0.18
abstract:           ~
author:
    - Ronan Waide <waider@waider.ie>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Date::Parse:       0
    HTML::Entities:    0
    HTML::TokeParser:  0
    WWW::Mechanize:    0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
